# Project information
site_name: Programmieren II
site_description: Lehrmaterial, Übungen, Aufgaben und Hilfen für Programmieren II
site_author: Jörn Freiheit & Vera Peuntinger
site_url: https://vrpntngr.github.io/programmieren2/

# Repository
repo_name: programmieren2
repo_url: https://github.com/vrpntngr/programmieren2

# Copyright
copyright: Copyright &copy; 2021 Jörn Freiheit

# Configuration
theme:
  name: material
  language: de
  palette:
    primary: grey
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - instant
    - tabs
  favicon: img/fiw.png
  logo: img/fiw.jpg

extra_css:
  - extra.css

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

#Navigation
nav:
  - Home: index.md
  - Wiederholung: wiederholung.md
  - Aufzählungstypen: enum.md
  - Wrapper-Klassen: wrapper.md
  - Exceptions: exceptions.md
  - Collections: collections.md
  - Maps: maps.md
  - Abstrakte Klassen: abstrakt.md
  - Interfaces: interfaces.md
  - Übungen: uebungen.md
  - Aufgaben: aufgaben.md

#  - Git: git.md
#  - Mehrdimensionale Arrays: mdarrays.md
#  - Aufzählungstypen: enum.md
#  - Exceptions: exceptions.md
#  - JUnit-Tests: junit.md
#  - Collections: collections.md
#  - Wrapper-Klassen: wrapper.md
#  - Maps: maps.md
#  - Abstrakte Klassen: abstrakt.md
#  - Interfaces: interfaces.md
#  - GUI Einführung: gui.md
#  - GUI Ereignisse: ereignisse.md
#  - GUI Graphics: graphics.md
#  - Mausereignisse: mausereignisse.md
#  - Klausurvorbereitung: klausurvorbereitung.md
#  - Übungen: uebungen.md
#  - Aufgaben: aufgaben.md
#  - Hilfen: hilfen.md
